// ============================================================
// WeekLog — js/pdf.js
// jsPDF-based PDF generation
// ============================================================

import { getEntries, getEntriesForDay, getStats, DAY_FULL } from './data.js';

const MARGIN = 18;
const PAGE_W = 210;
const INDIGO  = [127, 119, 221];
const INDIGO_DARK = [83, 74, 183];

/**
 * Generates and triggers download of the weekly PDF.
 * Requires jsPDF loaded globally via <script> tag.
 */
export async function generatePDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const draftText = document.getElementById('draft-body')?.innerText
    || 'No draft available. Log entries and regenerate.';

  const stats   = getStats();
  const entries = getEntries();

  // ── Header bar ──────────────────────────────────────────
  doc.setFillColor(...INDIGO);
  doc.rect(0, 0, PAGE_W, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Weekly Work Journal', MARGIN, 17);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Week ending Friday, 15 May 2026', MARGIN, 23);
  doc.text('Thabo Nkosi  ·  Engineering Team', PAGE_W - MARGIN, 23, { align: 'right' });

  // ── Summary section ─────────────────────────────────────
  let y = 38;
  y = drawSection(doc, 'SUMMARY', y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);

  const sumLines = doc.splitTextToSize(draftText, PAGE_W - MARGIN * 2);
  const cappedLines = sumLines.slice(0, 14);
  doc.text(cappedLines, MARGIN, y);
  y += cappedLines.length * 4.5 + 8;

  // ── Entries by day ───────────────────────────────────────
  y = drawSection(doc, 'ENTRIES BY DAY', y);

  ['Mon', 'Tue', 'Wed'].forEach(day => {
    const dayEntries = getEntriesForDay(day);
    if (!dayEntries.length) return;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...INDIGO_DARK);
    doc.text(DAY_FULL[day], MARGIN, y);
    y += 5;

    dayEntries.forEach(entry => {
      const COLOR_MAP = {
        done:  [29, 158, 117],
        prog:  [239, 159, 39],
        block: [226, 75, 74],
        meet:  [127, 119, 221],
      };
      const [r, g, b] = COLOR_MAP[entry.type] || [100, 100, 100];

      doc.setFillColor(r, g, b);
      doc.circle(MARGIN + 1.5, y - 1.5, 1.2, 'F');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(60, 60, 60);

      const lines = doc.splitTextToSize(entry.text, PAGE_W - MARGIN * 2 - 8);
      doc.text(lines, MARGIN + 5, y);
      y += lines.length * 4 + 1.5;

      if (y > 262) { doc.addPage(); y = 18; }
    });

    y += 3;
  });

  // ── Stats row ────────────────────────────────────────────
  y += 4;
  const bW = (PAGE_W - MARGIN * 2 - 8) / 3;
  const statDefs = [
    { label: 'Total entries', val: stats.total,  bg: [245, 245, 245], tc: [40,  40,  40]  },
    { label: 'Completed',     val: stats.done,   bg: [232, 245, 238], tc: [15,  110, 86]  },
    { label: 'Blocked',       val: stats.block,  bg: [255, 243, 224], tc: [226, 75,  74]  },
  ];
  statDefs.forEach((s, i) => {
    const x = MARGIN + i * (bW + 4);
    doc.setFillColor(...s.bg);
    doc.roundedRect(x, y, bW, 16, 2, 2, 'F');

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...s.tc);
    doc.text(String(s.val), x + bW / 2, y + 8, { align: 'center' });

    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text(s.label, x + bW / 2, y + 13, { align: 'center' });
  });

  // ── Footer on every page ─────────────────────────────────
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.text(
      `Generated by WeekLog · ${new Date().toLocaleDateString('en-ZA')} · Page ${p} of ${pages}`,
      PAGE_W / 2, 292, { align: 'center' }
    );
  }

  doc.save('WeekLog_w-e-15May2026_ThaboNkosi.pdf');
}

// ── Helper: section heading + divider ────────────────────
function drawSection(doc, title, y) {
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text(title, MARGIN, y);
  y += 5;

  doc.setDrawColor(...INDIGO);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  return y + 6;
}